답변 모달
Gila-part4/Gila pull request #18
Opened 2024-07-25 07:41 UTC by sj0724

답변모달 구현했습니다. 아직 데이터 넣는 부분까지는 안해뒀고 추후에 데이터 추가되면 진행하겠습니다.
<img width="536" alt="스크린샷 2024-07-25 오후 4 40 23" src="https://github.com/user-attachments/assets/c5ce8436-9b6d-4b9d-a193-632d1d9727df">
실제로 데이터 넣으면서 여러 상황에 대한 버그는 계속 수정하겠습니다!

2024-07-27 05:11 UTC, kuum97 requested changes
👍

2024-07-27 05:11 UTC, kuum97 commented on app/(protected)/(main)/question-list/_components/answer-list.tsx
> +      <div className="flex flex-col">
리스트는 ul 태그와 li 태그를 사용해주세요!

2024-07-27 05:11 UTC, kuum97 commented on app/(protected)/(main)/question-list/_components/answer-list.tsx
> +      <div className="flex flex-col overflow-y-scroll h-96 gap-2">
여기두 마찬가지로 ul 태그와 AnswerItem을 li 태그로 감싸서 li 태그에 key 연결해주세욥

2024-07-28 12:34 UTC, sj0724 commented on app/(protected)/(main)/question-list/_components/answer-list.tsx
> +      <div className="flex flex-col overflow-y-scroll h-96 gap-2">
변경했습니당

2024-07-29 04:21 UTC, kuum97 approved these changes

2024-07-29 04:55 UTC, juan0444 approved these changes

2024-07-29 04:56 UTC, merged