대시보드 리스트, 카드 구현
Gila-part4/Gila pull request #30
Opened 2024-07-26 11:39 UTC by Batrnan

- my-activity
<img width="338" alt="스크린샷 2024-07-26 오후 8 32 53" src="https://github.com/user-attachments/assets/f865822b-4e25-441a-9f12-f6f299e5cacf">

- my-question
<img width="338" alt="스크린샷 2024-07-26 오후 8 33 07" src="https://github.com/user-attachments/assets/3cb94e04-4094-4e5c-81f3-db0b8e69c33e">

- promise-list
<img width="342" alt="스크린샷 2024-07-26 오후 8 33 37" src="https://github.com/user-attachments/assets/238becd9-dc1f-4116-80f5-5a62784563a8">

- promised-list
<img width="342" alt="스크린샷 2024-07-26 오후 8 34 29" src="https://github.com/user-attachments/assets/899bb632-5a0a-425e-bbac-024dc8927bcc">

- reviews
<img width="342" alt="스크린샷 2024-07-26 오후 8 34 57" src="https://github.com/user-attachments/assets/23ea3700-d7c2-4d58-a7e0-7dac9713bf9b">

- wishlist
<img width="342" alt="스크린샷 2024-07-26 오후 8 35 17" src="https://github.com/user-attachments/assets/1c99078f-b4c2-4162-bd12-6cbebbade30b">

2024-07-26 23:47 UTC, sj0724 commented
너무 좋은데요? 작업량많았는데 수고하셨어요!

2024-07-27 05:38 UTC, kuum97 requested changes
커밋 분리 신경써주시면 좋을 것 같습니다ㅜㅜ 보기가 너무 힘듭니다ㅜㅜ

2024-07-27 05:38 UTC, kuum97 commented on app/(protected)/(user)/dashboard/_components/plus-button.tsx
> +  onClick?: () => void;
요거는 버튼 기본 타입이 있을텐데 그거 상속받으시면 될거같아요

2024-07-27 05:38 UTC, kuum97 commented on app/(protected)/(user)/dashboard/my-activity/_components/my-activity-card.tsx
> +      dropdownMenu={<DropdownKebab />}
해당 파일만 사용하는 컴포넌트라면 폴더 옮겨주세욥. 보기가 너무 힘듭니다 ㅜㅜ

2024-07-27 05:38 UTC, kuum97 commented on app/(protected)/(user)/dashboard/promise-list/_components/promise-status.tsx
> +}
텍스트 옆에 같은 컬러의 점까지 보여주는게 어떨까요? 아니면 모바일 사이즈에선 점만 보이게 해도 좋을꺼같아요!

2024-07-27 05:38 UTC, kuum97 commented on app/(protected)/(user)/dashboard/promise-list/_components/promise-list-card.tsx
> +        <div className="flex items-center w-full justify-between">
상태 표시하는 거 오른쪽 상단에 두시면 어떨까요? 그게 사용자들에게 익숙한느낌인거같아 제안드려 봅니다

2024-07-27 05:38 UTC, kuum97 commented on app/(protected)/(user)/dashboard/reviews/_components/rating-selector.tsx
> +    <div className="flex justify-between mt-2">
저 상수 배열은 컴포넌트 외부에서 선언해 주시고 지금처럼 map으로 배열을 표시해주고 싶을 때는 ul태그와 li태그를 사용해주세요!

2024-07-27 05:38 UTC, kuum97 commented on app/(protected)/(user)/dashboard/reviews/_components/reviews-card.tsx
> +  const [selectedRating, setSelectedRating] = useState('');
저희가 레이팅에 숫자가 들어갈 예정이라 number타입으로 바꿔주시면 좋을거 같습니다

2024-07-27 05:38 UTC, kuum97 commented on components/small-button.tsx
> +}
동일하게 기본 내장 타입 상속해주세요!

2024-07-27 05:51 UTC, juan0444 approved these changes

2024-07-30 06:51 UTC, kuum97 approved these changes

2024-07-30 06:52 UTC, merged