로고 랭크 파일 생성
Gila-part4/Gila pull request #40
Opened 2024-07-29 12:21 UTC by Batrnan

2024-07-30 10:44 UTC, Batrnan commented on app/(public)/introduction/rank-test/page.tsx
import는 나중에 수정하도록 하겠습니다

2024-07-31 05:12 UTC, kuum97 commented on app/(public)/introduction/rank-test/page.tsx
까먹을수도 있으니까 지금 수정해서 다시 푸시해주세요🤨

2024-07-31 12:37 UTC, sj0724 commented on package-lock.json
> +        "@faker-js/faker": "^8.4.1",
이건 어떤 라이브러리인가요?

2024-07-31 12:37 UTC, sj0724 commented on package-lock.json
여기에 엄청 추가된게 많은데 확인해봐야하지 않을까요..?

2024-08-01 04:19 UTC, kuum97 requested changes

2024-08-01 04:19 UTC, kuum97 commented on app/(public)/introduction/_components/profile-rank.tsx
> +};
랭크 상수 배열로 정리하고 메소드로 정리해주세요

2024-08-01 06:30 UTC, kuum97 commented on package-lock.json
> +        "@faker-js/faker": "^8.4.1",
더미데이터 추가 라이브러리

2024-08-01 06:30 UTC, kuum97 commented on package-lock.json
pr 경로 수정

2024-08-02 02:57 UTC, juan0444 approved these changes

2024-08-02 04:00 UTC, sj0724 approved these changes

2024-08-02 04:11 UTC, kuum97 approved these changes

2024-08-02 04:12 UTC, merged