대시보드 내비게이션 바 구현
Gila-part4/Gila pull request #49
Opened 2024-07-31 07:09 UTC by Batrnan

<img width="359" alt="스크린샷 2024-07-31 오후 4 05 53" src="https://github.com/user-attachments/assets/a0571ea0-2131-4d93-9805-d6d084af8428">

2024-07-31 12:41 UTC, sj0724 commented on app/(protected)/(user)/dashboard/_components/dashboard-nav.tsx
> +              <div
저는 이부분을 컴포넌트로 만들어서 관리하면 어떨까 싶은데 어떻게 생각하시나요?

2024-08-01 01:10 UTC, ghost approved these changes

2024-08-01 04:23 UTC, kuum97 requested changes

2024-08-01 04:23 UTC, kuum97 commented on app/(protected)/(user)/dashboard/_components/dashboard-nav.tsx
> +          const isActive = pathname === route.href;
선언은 배열메소드 내부가 아닌 리턴하기 전에 하셔야 할 것 같습니다.

2024-08-02 03:59 UTC, sj0724 approved these changes

2024-08-02 06:39 UTC, kuum97 approved these changes

2024-08-02 06:40 UTC, merged